version: '3.8'

networks:
  caldera-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  caldera_user1_conf:
  caldera_user1_data:
  caldera_user1_frontend:
  caldera_user2_conf:
  caldera_user2_data:
  caldera_user2_frontend:

services:
  caldera_user1:
    image: caldera:latest
    container_name: caldera_user1
    networks:
      caldera-net:
        ipv4_address: 172.18.0.10
    ports:
      - "8023:8022"
      - "8881:8888" 
    environment:
      - CALDERA_API_URL=http://10.6.2.87:8888
      - VITE_BASE_PATH=/user1/
      - VITE_CALDERA_API_URL=https://SERVER_ADDRESS/user1/
    command: ["--log", "DEBUG"]
    volumes:
      - caldera_user1_conf:/usr/src/app/conf
      - caldera_user1_data:/usr/src/app/data
      - caldera_user1_frontend:/usr/src/app/plugins/magma/dist/assets

  caldera_user2:
    image: caldera:latest
    container_name: caldera_user2
    networks:
      caldera-net:
        ipv4_address: 172.18.0.11
    ports:
      - "8022:8022" 
      - "8882:8888"
    environment:
      - CALDERA_API_URL=/SERVER_ADDRESS/
      - VITE_BASE_PATH=/user2/
      - VITE_CALDERA_API_URL=https://SERVER_ADDRESS/user2/
    command: ["--log", "DEBUG"]
    volumes:
      - caldera_user2_conf:/usr/src/app/conf
      - caldera_user2_data:/usr/src/app/data
      - caldera_user2_frontend:/usr/src/app/plugins/magma/dist/assets

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    networks:
      caldera-net:
        ipv4_address: 172.18.0.100
    ports:
      - "443:443"    
    volumes:
      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs  
      - caldera_user1_frontend:/usr/share/nginx/html/user1
      - caldera_user2_frontend:/usr/share/nginx/html/user2
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - caldera_user1
      - caldera_user2
      
