version: '3.8'

networks:
  caldera-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  caldera_user1_conf:
  caldera_user1_data:
  caldera_user2_conf:
  caldera_user2_data:

services:
  caldera_user1:
    build:
      context: .
      dockerfile: Dockerfile
    image: caldera:latest
    container_name: caldera_user1
    networks:
      caldera-net:
        ipv4_address: 172.18.0.10
    ports:
      - "8021:8022"
      - "8881:8888" 
    environment:
      - CALDERA_API_URL=https://192.168.105.2/user1  
    command: ["--log", "DEBUG"]
    volumes:
      - caldera_user1_conf:/usr/src/app/conf
      - caldera_user1_data:/usr/src/app/data

  caldera_user2:
    build:
      context: .
      dockerfile: Dockerfile
    image: caldera:latest
    container_name: caldera_user2
    networks:
      caldera-net:
        ipv4_address: 172.18.0.11
    ports:
      - "8022:8022" 
      - "8882:8888"
    environment:
      - CALDERA_API_URL=https://192.168.105.2/user2
    command: ["--log", "DEBUG"]
    volumes:
      - caldera_user2_conf:/usr/src/app/conf
      - caldera_user2_data:/usr/src/app/data

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    networks:
      caldera-net:
        ipv4_address: 172.18.0.100
    ports:
      - "8443:443"    
    volumes:
      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf 
      - ./certs:/etc/nginx/certs  
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - caldera_user1
      - caldera_user2

